### ISSUE TITLE
Should toRegex match path without explicit queries?

### ISSUE THREAD

**Issue by jbalsas** [metal/metal-path-parser#1]
Hi, I have a question regarding the `toRegex` method. Currently, unless explicitly specified, it won't match queries with paths. For example:

```javascript
it('should return regex that will match path without queries', function() {
    const regex = toRegex('/my/path');
    assert.ok(regex.test('/my/path?foo=bar'));
    assert.ok(regex.test('/my/path/?foo=bar'));
})
```

This means that one should create a route with all the possible query params or a wildcard.

Is this the expected behaviour?

**Comment by eduardolundgren** [comment]
If he is using metal-router it should work with the new version after this commit https://github.com/metal/metal-router/commit/57e1dcdaa1381701a75f728f95ecabcd7a5c5cdb.

**Comment by jbalsas** [comment]
Yeah, that should probably fix it... it requires `senna.js@2.1.0`, though, so it won't be immediate for us to update.

Closing here.

**Comment by eduardolundgren** [comment]
`senna.js@2.1.0` should be backward compatible with the one you are using.

**Comment by jbalsas** [comment]
Yeah, it's just that this one is released in portal, so for dxp we need to
update and backport the new version to the dxp dev branch.

It's just one extra step that we do regularly, and since we've fixed the
root issue that uncovered this, we don't really need it right away.
